<?php

namespace JF\CalendarBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventoRepository extends EntityRepository {

    public function calendarioMese(\JF\ACLBundle\Entity\Gestore $gestore, $mese, $anno) {
        $em = $this->getEntityManager();
        $conn = $em->getConnection();
        $stmt = $conn->executeQuery("
SELECT e.id 
  FROM jf_eventi e
 WHERE e.gestore_id = :gestore
   AND e.data_ora LIKE '{$anno}-{$mese}%'
            ", array('gestore' => $gestore->getId()));
        $out = $stmt->fetchAll();
        $ids = array(0);
        foreach ($out as $id){
            $ids[] = $id['id'];
        }
        return $this->findBy(array('id' => $ids), array('data_ora' => 'ASC'));
    }

}
