jf_git_hub:
    resource: "@JFGitHubBundle/Controller/"
    type:     annotation
    prefix:   /

slch:
    resource: "@SLCHBundle/Controller/"
    type:     annotation
    prefix:   /

scl_import:
    resource: "@SLCImportBundle/Controller/"
    type:     annotation
    prefix:   /

jf_calendar:
    resource: "@JFCalendarBundle/Controller/"
    type:     annotation
    prefix:   /

claims_ravinale:
    resource: "@ClaimsRavinaleBundle/Controller/"
    type:     annotation
    prefix:   /

claims_contec:
    resource: "@ClaimsContecBundle/Controller/"
    type:     annotation
    prefix:   /

claims_h:
    resource: "@ClaimsHBundle/Controller/"
    type:     annotation
    prefix:   /

claims_core:
    resource: "@ClaimsCoreBundle/Controller/"
    type:     annotation
    prefix:   /

jf_andreani:
    resource: "@JFAndreaniBundle/Controller/"
    type:     annotation
    prefix:   /

jf_acl:
    resource: "@JFACLBundle/Controller/"
    type:     annotation
    prefix:   /
    
jf_core:
    resource: "@JFCoreBundle/Controller/"
    type:     annotation
    prefix:   /
    
ephp_drag_drop:
    resource: "@EphpDragDropBundle/Controller/"
    type:     annotation
    prefix:   /

_fos:
    resource: routing_fos_user.yml
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
