security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        R_ADMIN:       ROLE_USER
        R_SUPER:       ROLE_ADMIN
        R_EPH:         [ROLE_USER, R_ADMIN, R_SUPER, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory:
                users:
                    dodo:  { password: pci, roles: [ 'ROLE_SUPER_ADMIN' ] }

    firewalls:
        github:
            pattern:  ^/github/
            security: false
        andreani:
            pattern:  ^/andreani/
            security: false
        cron:
            pattern:  -cron$
            security: false
        eph:
            pattern:  /eph$
            security: false
        push:
            pattern:  /push$
            security: false
        get:
            pattern:  /get$
            security: false
        work:
            pattern:  /(_wdt)|(js)
            security: false
        login:
            pattern:  ^/login$
            security: false
 
            remember_me:
                key: "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER
        main:
            remember_me:
                key: divine_office_hub_17021976
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER                   
                always_remember_me: true
                remember_me_parameter: _remember_me
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login
                check_path: /login_check
                success_handler: my_user_provider        
            logout:
                path: /logout
                target: /
                invalidate_session: false # Provissorio per il 5.11
            anonymous:    false

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
