<?php

namespace Claims\HAuditBundle\Entity;

use Doctrine\ORM\EntityRepository;
use JF\ACLBundle\Entity\Cliente;

/**
 * AuditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuditRepository extends EntityRepository {
    
    public function getAudit(Cliente $cliente) {
        return $this->createQueryBuilder('a')
                ->where('a.cliente = :cliente')
                ->setParameter('cliente', $cliente->getId());
    }
    
}
