<?php

namespace Claims\HAuditBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AuditQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuditQuestionRepository extends EntityRepository
{
}
