<?php

namespace Claims\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StatoPraticaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatoPraticaRepository extends EntityRepository
{
}
