<table width="100%" border="0" cellspacing="0" cellpadding="2">
    <tr class="even">
        <td id="tdt" align="left"  width="13%" >31/10/2013 09:46:00</td>
        <td id="tdt" align="left"  width="12%" >Luigi Faraone Mennella</td>
        <td id="tdt" align="left"  width="15%" >
            <a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='135527'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='135527'; document.mainForm.submit();>Comunicazione</a>
        </td>
        <td id="tdt" align="left"  width="53%" >Re: Re: Re: Re: Re: Re: USAI aggiornamento su giudiziale</td>
        <td id="tdt" align="left"  width="7%" ></td>
    </tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >29/08/2013 16:57:44</td><td id="tdt" align="left"  width="12%" >Marco Aste</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='129041'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='129041'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >Re: Re: Re: Re: Re: USAI aggiornamento su giudiziale</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >28/08/2013 11:35:56</td><td id="tdt" align="left"  width="12%" >Luigi Faraone Mennella</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='128900'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='128900'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >Re: Re: Re: Re: USAI aggiornamento su giudiziale</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >24/04/2013 15:07:24</td><td id="tdt" align="left"  width="12%" >Luigi Faraone Mennella</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='118650'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='118650'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >Re: Usai Francesco CGL- aggiornamento su giudizio</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >04/02/2013 11:52:37</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" >Storico stati</td><td id="tdt" align="left"  width="53%" >In attesa consulente legale</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >17/01/2013 18:40:48</td><td id="tdt" align="left"  width="12%" >Maria Pia Capitini</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='109586'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='109586'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >Usai Francesco CGL- aggiornamento su giudizio</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >08/11/2012 17:34:48</td><td id="tdt" align="left"  width="12%" >Marco Aste</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='103732'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='103732'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >Re: Re: Re: USAI aggiornamento su giudiziale</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >08/11/2012 11:15:18</td><td id="tdt" align="left"  width="12%" >Luigi Faraone Mennella</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='103662'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='103662'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >Re: Re: USAI aggiornamento su giudiziale</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >04/10/2012 15:50:41</td><td id="tdt" align="left"  width="12%" >Luigi Faraone Mennella</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='100593'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='100593'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >Re: USAI aggiornamento su giudiziale</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >03/07/2012 19:08:02</td><td id="tdt" align="left"  width="12%" >Alberto Carlesi</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='93188'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='93188'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >USAI aggiornamento su giudiziale</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >03/07/2012 19:05:06</td><td id="tdt" align="left"  width="12%" >Luigi Faraone Mennella</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='93187'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='93187'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >Per avv. Aste: aggiornamento su giudiziale</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd">
        <td id="tdt" align="left"  width="13%" >15/06/2012</td>
        <td id="tdt" align="left"  width="12%" ></td>
        <td id="tdt" align="left"  width="15%" >
            <a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=117391'>Documento allegato</a>
        </td>
        <td id="tdt" align="left"  width="53%" >Act of summons/Legal documents - Aggiornamento causa</td>
        <td id="tdt" align="left"  width="7%" ></td>
    </tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >28/05/2012 11:34:47</td><td id="tdt" align="left"  width="12%" >Luana Riedi</td><td id="tdt" align="left"  width="15%" onmouseover="document.body.style.cursor = 'pointer'; " onclick="toolTip('prova', 400);"  onmouseout="document.body.style.cursor = 'auto'; toolTip();" >Nota lavorazione</td><td id="tdt" align="left"  width="53%" onmouseover="document.body.style.cursor = 'pointer'; " onclick="toolTip('prova', 400);"  onmouseout="document.body.style.cursor = 'auto'; toolTip();" >prova</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >27/03/2012 12:53:57</td><td id="tdt" align="left"  width="12%" >Ludovica Giuri</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='83825'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='83825'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >Re: usai francesco  aggiornamento da ns CTP </td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >23/03/2012 16:44:32</td><td id="tdt" align="left"  width="12%" >Alberto Carlesi</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='83510'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='83510'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >usai francesco  aggiornamento da ns CTP </td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >23/03/2012 12:29:53</td><td id="tdt" align="left"  width="12%" >Marco Aste</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='83472'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='83472'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >Re: Per avvocati: aggiornamento/esito CTU </td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >22/03/2012 11:28:13</td><td id="tdt" align="left"  width="12%" >Luigi Faraone Mennella</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='83308'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='83308'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >Per avvocati: aggiornamento/esito CTU </td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >19/09/2011 08:45:24</td><td id="tdt" align="left"  width="12%" >Luigi Faraone Mennella</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='67546'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='67546'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >Per tutti: aggiornamento </td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >09/07/2011</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=77578'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >Act of summons/Legal documents - aggiornamento avv aste</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >05/07/2011</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=77238'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >Update Court case from Lawyer - Risposta avvocato su andamento causa</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >06/06/2011</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=73451'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >Update Court case from Lawyer - Richiesta andamento processuale persone</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >30/03/2011 23:59:59</td><td id="tdt" align="left"  width="12%" >Luigi Faraone Mennella</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='56031'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='56031'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >Aggiornamento da fuori sistema </td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >30/03/2011</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=65619'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >Message attachment</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >29/12/2010</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=54294'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >Contec mail (IN)</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >26/10/2010 10:19:28</td><td id="tdt" align="left"  width="12%" >Luigi Faraone Mennella</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='44874'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='44874'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >Aggiornamento su giudiziale </td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >17/02/2010 18:06:39</td><td id="tdt" align="left"  width="12%" >Luigi Faraone Mennella</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='31079'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='31079'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >CGL-Usai: riserva e sviluppi giudiziale</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >27/01/2010 10:58:20</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" >Storico riserva</td><td id="tdt" align="left"  width="53%" >Stima certa: 30.000,00 - </td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >26/01/2010 13:46:55</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='29976'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='29976'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >RE: Report per Newline</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >26/01/2010 12:21:57</td><td id="tdt" align="left"  width="12%" >Mauro Rattalino</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='29960'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='29960'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >fwd: RE: USAI relazione 22122009</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >26/01/2010 10:31:50</td><td id="tdt" align="left"  width="12%" >Alberto Carlesi</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='29942'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='29942'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >Re: Report per Newline</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >26/01/2010 09:21:25</td><td id="tdt" align="left"  width="12%" >Mauro Rattalino</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='29931'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='29931'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >Report per Newline</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >26/01/2010</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=32583'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >Message attachment - usai relazione prof. Usai.pdf</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >26/01/2010</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=32582'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >Message attachment - COMPARSAASL8.USAI.DOC</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >09/01/2010 11:41:11</td><td id="tdt" align="left"  width="12%" >Mauro Rattalino</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='29141'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='29141'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >Comparsa pervenuta da Avv. Aste</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >09/01/2010</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=32039'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >Act of summons/Legal documents</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >30/12/2009 11:40:39</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='28632'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='28632'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >RE: USAI relazione 22122009</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >30/12/2009 11:07:16</td><td id="tdt" align="left"  width="12%" >Luigi Faraone Mennella</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='28622'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='28622'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >Re: LT updating - correction</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >29/12/2009 19:15:58</td><td id="tdt" align="left"  width="12%" >Luigi Faraone Mennella</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='28600'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='28600'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >LT updating </td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >29/12/2009 18:25:18</td><td id="tdt" align="left"  width="12%" >Luigi Faraone Mennella</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='28597'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='28597'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >Re: USAI relazione 22122009</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >29/12/2009 17:55:18</td><td id="tdt" align="left"  width="12%" >Alberto Carlesi</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='28591'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='28591'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >Re: USAI relazione 22122009</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >29/12/2009 17:42:16</td><td id="tdt" align="left"  width="12%" >Mauro Rattalino</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='28587'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='28587'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >Re: USAI relazione 22122009</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >29/12/2009</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=31579'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >Medical Examiner/Specialist report</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >29/12/2009</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=31578'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >ULSS Bedside instruction</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >22/12/2009 23:59:59</td><td id="tdt" align="left"  width="12%" >Alberto Carlesi</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='28316'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='28316'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >USAI relazione 22122009</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >22/12/2009 13:53:11</td><td id="tdt" align="left"  width="12%" >Francesco De Stefano</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='28312'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='28312'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >Re: Incarico peritale</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >22/12/2009 13:53:10</td><td id="tdt" align="left"  width="12%" >Francesco De Stefano</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='28311'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='28311'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >Re: USAI atto di citazione comunicazione 141209</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >22/12/2009</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=31223'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >Message attachment</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >22/12/2009</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=31216'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >Message attachment - USAI_22_12_09.pdf</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >22/12/2009</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=31215'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >Message attachment - USAI_22_12_09.pdf</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >15/12/2009 12:04:15</td><td id="tdt" align="left"  width="12%" >Mauro Rattalino</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='27838'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='27838'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >Incarico peritale</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >15/12/2009 12:01:17</td><td id="tdt" align="left"  width="12%" >Mauro Rattalino</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='27837'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='27837'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >Incarico per udienza del 28.01.10</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >15/12/2009</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=30902'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >Appointment to Medical Examiner - Incarico Medico Legale</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >15/12/2009</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=30901'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >Appointmeto to other Lawyer - Incarico altro Avvocato</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >14/12/2009 19:09:47</td><td id="tdt" align="left"  width="12%" >Francesco De Stefano</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='27803'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='27803'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >Re: USAI atto di citazione comunicazione 141209</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >14/12/2009 17:26:54</td><td id="tdt" align="left"  width="12%" >Alberto Carlesi</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='27789'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='27789'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >USAI richiesta polizze personali</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >14/12/2009 12:06:31</td><td id="tdt" align="left"  width="12%" >Alberto Carlesi</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='27751'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='27751'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >USAI atto di citazione comunicazione 141209</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >14/12/2009</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=30855'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >Message attachment</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >13/12/2009 15:25:17</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" >Storico stati</td><td id="tdt" align="left"  width="53%" >Sinistro in azione giudiziale</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >13/12/2009</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=30814'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >Act of summons/Legal documents</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >21/08/2009 11:17:48</td><td id="tdt" align="left"  width="12%" >Mauro Rattalino</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='17380'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='17380'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >Ulteriore documentazione</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >21/08/2009</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=17851'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >Contec mail (IN)</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >10/06/2009 13:35:27</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" >Storico stati</td><td id="tdt" align="left"  width="53%" >Respinto - Responsabilità negata</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >23/02/2009 14:05:29</td><td id="tdt" align="left"  width="12%" >Luigi Faraone Mennella</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='9779'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='9779'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >Letter from the claimants lawyers </td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >23/02/2009 10:43:14</td><td id="tdt" align="left"  width="12%" >Alberto Carlesi</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='9767'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='9767'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >-</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >22/02/2009 15:03:28</td><td id="tdt" align="left"  width="12%" >Mauro Rattalino</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='9753'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='9753'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >Sollecito</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >22/02/2009</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=8412'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >Contec mail (IN) - Sollecito</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >16/01/2009</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=7664'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >Contec mail (IN)</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >14/01/2009 17:32:03</td><td id="tdt" align="left"  width="12%" >Mauro Rattalino</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='8755'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='8755'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >Comunicazione</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >14/01/2009</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=7608'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >Contec mail (IN)</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >01/08/2008</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=2981'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >Survey</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >01/08/2008</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=2948'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >Medical Examiner/Specialist report</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >01/08/2008</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=2923'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >Appointment to Medical Examiner</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >01/08/2008</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=2905'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >ULSS Bedside instruction</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >01/08/2008</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=2834'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >Privacy documentation</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >01/08/2008</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=2827'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >Legal Team report</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >01/08/2008</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=2798'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >Appointment to Legal Team</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >01/08/2008</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=2768'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >Contec mail (IN)</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >01/08/2008</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=2745'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >Contec mail (OUT)</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >01/08/2008</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=2719'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >Claim</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >01/08/2008</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=2700'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >ULSS mail</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >01/08/2008</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href='/jwcmedmal/servizi/ScaricaDocumentoGED?id=2649'>Documento allegato</a></td><td id="tdt" align="left"  width="53%" >Notification of claim</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >01/02/2008 09:55:10</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" >Storico stati</td><td id="tdt" align="left"  width="53%" >Sinistro respinto</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >24/01/2008 13:42:31</td><td id="tdt" align="left"  width="12%" >Luigi Faraone Mennella</td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='4474'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='4474'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >English Report</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >17/12/2007 17:53:58</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='4311'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.visualizzaComunicazione'; document.mainForm.parameters.value='4311'; document.mainForm.submit();>Comunicazione</a></td><td id="tdt" align="left"  width="53%" >Sinistro USAI CGL/07/03</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >29/11/2007 11:14:12</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" >Storico riserva</td><td id="tdt" align="left"  width="53%" >Stima iniziale: 1.000.000,00 - </td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >28/11/2007 13:02:04</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" >Storico riserva</td><td id="tdt" align="left"  width="53%" >Stima certa: 200.000,00 - </td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >27/11/2007 16:27:10</td><td id="tdt" align="left"  width="12%" >Secchi Diana</td><td id="tdt" align="left"  width="15%" >Inserimento sinistro</td><td id="tdt" align="left"  width="53%" ></td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="odd"><td id="tdt" align="left"  width="13%" >12/09/2007</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" ><a class='azione' href="javascript:document.mainForm.actionRequired.value='schedaTrattazioneSinistro.preparaIncaricoSinistro'; document.mainForm.parameters.value='3396'; document.mainForm.submit();" document.mainForm.actionRequired.value='schedaTrattazioneSinistro.preparaIncaricoSinistro'; document.mainForm.parameters.value='3396'; document.mainForm.submit();>Consulente</a></td><td id="tdt" align="left"  width="53%" >Carlesi Alberto</td><td id="tdt" align="left"  width="7%" ></td></tr>
    <tr class="even"><td id="tdt" align="left"  width="13%" >07/09/2007 00:00:00</td><td id="tdt" align="left"  width="12%" ></td><td id="tdt" align="left"  width="15%" >Storico riserva</td><td id="tdt" align="left"  width="53%" > - Sinistro in corso/in istruttoria</td><td id="tdt" align="left"  width="7%" ></td></tr>
</table>


\(\);"[^>]*>
();">